name: Deploy - Prod

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install
        working-directory: ./server

      - name: Correr testes
        run: npm test
        working-directory: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy para Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: kiwa-prod-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: ./server